name: My Secrets App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      apikey: ${{ secrets.APIKEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: MySecretsApp
