name: My Secrets App

on:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest

    env:
      apikey: ${{ secrets.APIKEY }}
      sendgrid_api_key: ${{ secrets.APIKEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Restore dependencies
        run: dotnet restore MySecretsApp/MySecretsApp.csproj

      - name: Build
        run: dotnet build MySecretsApp/MySecretsApp.csproj --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: MySecretsApp
